Script logic
MapColonies/raster-publishing-cli pull request #1
Opened 2022-02-06 14:38 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✔                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-02-07 08:53 UTC, asafMasa requested changes
remove helm files
throw error on update scenario "Not Supported"
basic readme about with the link to excel parameters

2022-02-07 08:53 UTC, asafMasa commented on src/publishCommand/publishManager.ts
> +    //await this.metadataValidator.validate(metadata);
remarks

2022-02-07 08:53 UTC, asafMasa commented on tests/integration/publishCommand/publishCommand.spec.ts
> +    // consoleLogMock = jest.spyOn(global.console, 'log');
remarks

2022-02-07 08:53 UTC, asafMasa commented on tests/integration/publishCommand/publishCommand.spec.ts
> +  // let consoleLogMock: jest.SpyInstance;
remarks

2022-02-07 08:53 UTC, asafMasa commented on tests/integration/publishCommand/publishCommand.spec.ts
> +    //overriding  containers that are registered with decorators dont work with current implementation
remarks

2022-02-07 12:31 UTC, asafMasa approved these changes

2022-02-07 12:42 UTC, asafMasa approved these changes

2022-02-08 13:15 UTC, AnguIar approved these changes

2022-02-08 13:17 UTC, AnguIar approved these changes

2022-02-08 13:17 UTC, AnguIar commented
בס"ד
ישר כוח

2022-02-08 14:12 UTC, merged